/*
BASED ON: rptSIS743_SSSPEvaluationDetails (as of September 28, 2017)

*/

use [Student_Records_copy];
--Challenges

select 
SR_STUDENT_TERMS.PERSON_ID,
SR_STUDENT_TERMS.TERM_ID,
ENGL_C = case when A.COURSE_DISCIPLINE = 'ENGL' then A.COURSE_DISCIPLINE_NBR end, 
ENGL_C_DIGITS = case when A.COURSE_DISCIPLINE = 'ENGL' then A.COURSE_DIGITS end,
MATH_C = case when A.COURSE_DISCIPLINE = 'MATH' then A.COURSE_DISCIPLINE_NBR end, 
MATH_C_DIGITS = case when A.COURSE_DISCIPLINE = 'MATH' then A.COURSE_DIGITS end,
ESL_C = case when A.COURSE_DISCIPLINE = 'ESL' then A.COURSE_DISCIPLINE_NBR end, 
ESL_C_DIGITS = case when A.COURSE_DISCIPLINE = 'ESL' then A.COURSE_DIGITS end,
CHEM_C = case when A.COURSE_DISCIPLINE = 'CHEM' then A.COURSE_DISCIPLINE_NBR end, 
CHEM_C_DIGITS = case when A.COURSE_DISCIPLINE = 'CHEM' then A.COURSE_DIGITS end
from SR_STUDENT_TERMS inner join
--Latest equivalency
(select PERSON_ID, MAX(CHALLENGES_ID) as CHALLENGES_ID, MAX(b.COURSE_ID) as COURSE_ID, 
MAX(b.VERSION_NBR) as VERSION_NBR, MAX(SR_COURSE_VERSIONS.COURSE_DISCIPLINE_NBR) as COURSE_DISCIPLINE_NBR, 
MAX(SR_COURSE_VERSIONS.COURSE_DIGITS) as COURSE_DIGITS, MAX(SR_COURSE_VERSIONS.COURSE_DISCIPLINE) as COURSE_DISCIPLINE
from SR_STUDENT_CHALLENGES inner join
(select COURSE_ID, MAX(VERSION_NBR) AS VERSION_NBR from SR_COURSE_VERSIONS WHERE APPROVAL_STATUS = 7 GROUP BY COURSE_ID) B 
	on SR_STUDENT_CHALLENGES.COURSE_ID = B.COURSE_ID INNER JOIN
SR_COURSE_VERSIONS ON B.COURSE_ID = SR_COURSE_VERSIONS.COURSE_ID AND B.VERSION_NBR = SR_COURSE_VERSIONS.VERSION_NBR 
Where SR_STUDENT_CHALLENGES.ACTIVE_STATUS = 1
and SR_STUDENT_CHALLENGES.DATE_CLEARED IS NULL
and SR_COURSE_VERSIONS.COURSE_DISCIPLINE  in ('ENGL', 'MATH', 'ESL', 'CHEM')
group by PERSON_ID, SR_COURSE_VERSIONS.COURSE_DISCIPLINE
) A  on A.PERSON_ID = SR_STUDENT_TERMS.PERSON_ID  inner join
SR_STUDENT_CHALLENGES on A.CHALLENGES_ID = SR_STUDENT_CHALLENGES.CHALLENGES_ID 
where SR_STUDENT_TERMS.TERM_ID = 20177 /* HERE */
