/*
BASED ON: rptSIS743_SSSPEvaluationDetails (as of September 28, 2017)

*/

use [Student_Records_copy];

select
SR_STUDENT_TERMS.PERSON_ID,
SR_STUDENT_TERMS.TERM_ID,
ENGL_E = case when A.COURSE_DISCIPLINE = 'ENGL' then A.COURSE_DISCIPLINE_NBR end, 
ENGL_E_DIGITS = case when A.COURSE_DISCIPLINE = 'ENGL' then A.COURSE_DIGITS end,
MATH_E = case when A.COURSE_DISCIPLINE = 'MATH' then A.COURSE_DISCIPLINE_NBR end, 
MATH_E_DIGITS = case when A.COURSE_DISCIPLINE = 'MATH' then A.COURSE_DIGITS end,
ESL_E = case when A.COURSE_DISCIPLINE = 'ESL' then A.COURSE_DISCIPLINE_NBR end, 
ESL_E_DIGITS = case when A.COURSE_DISCIPLINE = 'ESL' then A.COURSE_DIGITS end,
CHEM_E = case when A.COURSE_DISCIPLINE = 'CHEM' then A.COURSE_DISCIPLINE_NBR end, 
CHEM_E_DIGITS = case when A.COURSE_DISCIPLINE = 'CHEM' then A.COURSE_DIGITS end
from 
	SR_STUDENT_TERMS inner join
--Latest equivalency
(
	select PERSON_ID, 
	MAX(EQUIVALENCIES_ID) as EQUIVALENCIES_ID, 
	MAX(b.COURSE_ID) as COURSE_ID, 
	MAX(b.VERSION_NBR) as VERSION_NBR,
	MAX(SR_COURSE_VERSIONS.COURSE_DISCIPLINE_NBR) as COURSE_DISCIPLINE_NBR, 
	MAX(SR_COURSE_VERSIONS.COURSE_DIGITS) as COURSE_DIGITS, 
	MAX(SR_COURSE_VERSIONS.COURSE_DISCIPLINE) as COURSE_DISCIPLINE
	from SR_STUDENT_EQUIVALENCIES 
	inner join
	(
	select COURSE_ID, 
		MAX(VERSION_NBR) AS VERSION_NBR from SR_COURSE_VERSIONS WHERE APPROVAL_STATUS = 7 GROUP BY COURSE_ID
	) as B 
		on SR_STUDENT_EQUIVALENCIES.COURSE_ID = B.COURSE_ID 
	inner join
	SR_COURSE_VERSIONS 
		on B.COURSE_ID = SR_COURSE_VERSIONS.COURSE_ID AND B.VERSION_NBR = SR_COURSE_VERSIONS.VERSION_NBR 
	where SR_STUDENT_EQUIVALENCIES.ACTIVE_STATUS = 1
	and SR_STUDENT_EQUIVALENCIES.DATE_CLEARED IS NULL
	and SR_COURSE_VERSIONS.COURSE_DISCIPLINE in ('ENGL', 'MATH', 'ESL', 'CHEM')

	group by PERSON_ID, SR_COURSE_VERSIONS.COURSE_DISCIPLINE
) as A  
on A.PERSON_ID = SR_STUDENT_TERMS.PERSON_ID  
inner join
	SR_STUDENT_EQUIVALENCIES 
on A.EQUIVALENCIES_ID = SR_STUDENT_EQUIVALENCIES.EQUIVALENCIES_ID 
where SR_STUDENT_TERMS.TERM_ID = 20177 /* HERE */
;