/*
BASED ON: rptSIS743_SSSPEvaluationDetails (as of September 28, 2017)

*/

use [Student_Records_copy];

select
SR_STUDENT_TERMS.PERSON_ID,
SR_STUDENT_TERMS.TERM_ID,
SR_COURSE_VERSIONS.COURSE_DISCIPLINE_NBR as ENGL_P,
SR_COURSE_VERSIONS.COURSE_DIGITS as ENGL_DIGITS
from  SR_STUDENT_TERMS 
inner join
	(select PERSON_ID, MAX(SCORE_ID) as SCORE_ID from SR_STUDENT_SCORES A inner join SR_TESTS B on A.TEST_ID = B.TEST_ID
	where B.PLACEMENT_TYPE = 1 --TEST_ID in (14, 48, 51) 
	and A.TERM_APPLICABLE <= 20177 /* HERE */
	and A.TERM_EXPIRES >= 20177 /* HERE */
	and A.ACTIVE_STATUS > 0
	and A.COURSE_ID <> 0 -- no placement
	group by PERSON_ID) as AA
on SR_STUDENT_TERMS.PERSON_ID = AA.PERSON_ID and SR_STUDENT_TERMS.TERM_ID = 20177 /* HERE */
inner join
	SR_STUDENT_SCORES 
on AA.SCORE_ID = SR_STUDENT_SCORES.SCORE_ID 
inner join
	(select COURSE_ID, max(VERSION_NBR) AS VERSION_NBR from SR_COURSE_VERSIONS where APPROVAL_STATUS = 7 group by COURSE_ID) B 
on case when SR_STUDENT_SCORES.COURSE_ID = 2721 then 7474 else SR_STUDENT_SCORES.COURSE_ID end = B.COURSE_ID 

inner join
	SR_COURSE_VERSIONS 
on B.COURSE_ID = SR_COURSE_VERSIONS.COURSE_ID and B.VERSION_NBR = SR_COURSE_VERSIONS.VERSION_NBR 
order by aa.PERSON_ID

